### ISSUE TITLE
Please add this feature

### ISSUE THREAD

**Issue by sasdallas** [marcocorriero/Fnaf-VR-HW-Mod-menu#1]
Please make this work on the Oculus Version if you can. They should have fixed the GObjects and GNames(lol if I mixup)

Be amazing if you did

**Comment by ghost** [comment]
I wish i could, but is the tool that finds the GNames and Gobjects, not me.
Is hard to use the dumped SDK, im following the progress until it gets good enought, if so, ill revive this project.

**Comment by sasdallas** [comment]
oh ok.

im noob game dev

thx for replying
